#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# app_login:
#     path: /login
#     methods: ['POST', 'GET']
#     controller: 'App\Controller\LoginController'
app_logout:
    path: /logout
    methods: ['POST', 'GET']